name: Update LeetCode Stats in README

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Fetch LeetCode stats using a script
      - name: Fetch LeetCode Stats
        run: |
          echo "Fetching LeetCode stats..."
          # Replace <your_username> with your LeetCode username
          curl -s "https://leetcode-stats-api.herokuapp.com/<your_username>" > leetcode_stats.json

      # Step 3: Generate README content
      - name: Update README with LeetCode Stats
        run: |
          echo "Updating README..."
          # Extract stats from the JSON
          TOTAL_SOLVED=$(jq -r '.totalSolved' leetcode_stats.json)
          RANK=$(jq -r '.ranking' leetcode_stats.json)

          # Insert stats into README
          sed -i '/<!--START_LEETCODE_STATS-->/,/<\!--END_LEETCODE_STATS-->/c\
          <!--START_LEETCODE_STATS-->\
          - 🏆 **LeetCode Rank:** $RANK\
          - ✅ **Total Problems Solved:** $TOTAL_SOLVED\
          <!--END_LEETCODE_STATS-->' README.md

      # Step 4: Commit and push changes
      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "Update LeetCode Stats [skip ci]"
          git push
